-- Migration: initial_schema
-- Project: Oudora
-- Generated by: Database Engineer Agent

BEGIN;

-- ── EXTENSIONS ──────────────────────────────────────────────────────────────
-- Ensure UUID extension is available (standard in Supabase)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── TABLES ──────────────────────────────────────────────────────────────────

-- Table: leads
CREATE TABLE IF NOT EXISTS public.leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── INDEXES ─────────────────────────────────────────────────────────────────

-- Index for lead email lookups/uniqueness check
CREATE INDEX IF NOT EXISTS idx_leads_email ON public.leads(email);

-- ── UPDATED_AT TRIGGER ───────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.leads
  FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();

-- ── ROW LEVEL SECURITY ───────────────────────────────────────────────────────

ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Policy: Public can insert (allow users to submit the form)
CREATE POLICY "Enable insert for public" ON public.leads
  FOR INSERT 
  WITH CHECK (true);

-- Policy: Authenticated users (Admin) can select
CREATE POLICY "Enable select for authenticated users only" ON public.leads
  FOR SELECT 
  TO authenticated
  USING (true);

COMMIT;